# Generated by Django 5.2.3 on 2025-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('computer_science', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('economics', 'Economics'), ('psychology', 'Psychology'), ('engineering', 'Engineering'), ('business', 'Business'), ('arts', 'Arts & Literature'), ('philosophy', 'Philosophy'), ('social_studies', 'Social Studies'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
