# Generated by Django 5.2.3 on 2025-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('economics', 'Economics'), ('psychology', 'Psychology'), ('engineering', 'Engineering'), ('business', 'Business'), ('arts', 'Arts & Literature'), ('philosophy', 'Philosophy'), ('social_studies', 'Social Studies'), ('computer_science', 'Computer Science'), ('python', 'Python Programming'), ('javascript', 'JavaScript'), ('java', 'Java Programming'), ('cpp', 'C/C++ Programming'), ('csharp', 'C# Programming'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('artificial_intelligence', 'Artificial Intelligence'), ('database', 'Database & SQL'), ('algorithms', 'Algorithms & Data Structures'), ('software_engineering', 'Software Engineering'), ('cybersecurity', 'Cybersecurity'), ('networking', 'Computer Networking'), ('operating_systems', 'Operating Systems'), ('game_development', 'Game Development'), ('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('devops', 'DevOps & Cloud'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
